### ISSUE TITLE
tvdb_id 81400 (Naked Science) is a 404

### ISSUE THREAD

**Issue by bricky** [midgetspy/sb_tvdb_scene_exceptions#23]
Regarding [this line](https://github.com/midgetspy/sb_tvdb_scene_exceptions/blob/gh-pages/exceptions.txt#L70):

```
81400: 'National Geographic Channel Naked Science', 'National Geographic Naked Science',
```

It looks like that show is gone on thetvdb: 
http://thetvdb.com/?tab=series&id=81400&lid=7

(not a 404 granted, but it's empty, and the series xml _is_ a 404).

It looks like the series has been moved to here:
http://thetvdb.com/?tab=seasonall&id=80994&lid=7

... it matches many of the episode names in [the associated tv.com page](http://www.tv.com/shows/naked-science/episodes/).

So, any chance we could change `81400` to `80994`?

**Comment by thezoggy** [comment]
sure, but looks like they changed the S#E# to S####E#. so nothing is going to work for this show until people rename all their files...

**Comment by thezoggy** [comment]
corrected id

**Comment by bricky** [comment]
Thanks zoggy :)

**Comment by thezoggy** [comment]
You will need to delete the cache.db file and start up SB to make sure the old exception isn't used 

-----Original Message-----
